name: Build

on:
  workflow_dispatch:
    inputs:
      electron-linux:
        default: 'true'
        type: boolean
      electron-windows:
        default: 'true'
        type: boolean
      electron-mac:
        default: 'true'
        type: boolean
      android:
        default: 'true'
        type: boolean
      browser:
        default: 'true'
        type: boolean

jobs:
  build-linux:
    runs-on: ubuntu-latest
    if: ${{ inputs.electron-linux }}
    steps:
      - uses: actions/checkout@v3

      - uses: bahmutov/npm-install@v1
      
      - name: Build
        run: npm run build-linux
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-linux
          path: platforms/electron/build
  
  build-windows:
    runs-on: windows-latest
    if: ${{ inputs.electron-windows }}
    steps:
      - uses: actions/checkout@v3

      - uses: bahmutov/npm-install@v1
      
      - name: Build
        run: npm run build-windows
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-windows
          path: platforms/electron/build
  
  build-mac:
    runs-on: macos-latest
    if: ${{ inputs.electron-mac }}
    steps:
      - uses: actions/checkout@v3

      - uses: bahmutov/npm-install@v1
      
      - name: Build
        run: npm run build-mac
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-mac
          path: platforms/electron/build

  build-android:
    runs-on: ubuntu-latest
    if: ${{ inputs.android }}
    steps:
      - uses: actions/checkout@v3
        
      - name: Set up JDK 
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
            
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - uses: bahmutov/npm-install@v1
      
      - name: Build
        run: npm run build-android
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-android
          path: platforms/android/app/build/outputs/

  build-browser:
    runs-on: ubuntu-latest
    if: ${{ inputs.browser }}
    steps:
      - uses: actions/checkout@v3

      - uses: bahmutov/npm-install@v1
      
      - name: Build
        run: npm run build-browser
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-browser
          path: platforms/browser/www/
